### ISSUE TITLE
プロジェクト進行の新機能

### ISSUE THREAD

**Issue by Meary166** [MonsterLifeServer/HomePage#7]
- ClosedされていないIssueをプロジェクト進捗に加える
  - `/repos/{owner}/{repo}`を使えば`open_issues_count`という項目を取得できる
- プロジェクト更新日の表示機能
  - `/repos/{owner}/{repo}`を使えば`updated_at`という項目を取得できる
- プロジェクト更新日が新しいもの順に表示する機能
  - `/repos/{owner}/{repo}`を使えば`updated_at`という項目を取得できる
- デフォルトブランチの自動取得機能
   - `/repos/{owner}/{repo}`を使えば`default_branch`という項目を取得できる
- 最新コミッターを表示する機能(方法不明)

**Comment by hashimotok-delien** [comment]
最新コミッターを表示する機能(方法不明)のみ検討中
それ以外は実装
